# Generated by Django 6.0.4 on 2026-06-17 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenUsuario',
        ),
    ]
